import type {
  Product,
  Category,
  Deal,
  Review,
  StoreHours,
  StoreInfo,
} from "@/types";
import { deepFoodsGroceryProducts, deepFoodsFrozenProducts } from "./deepFoodsProducts";
import { radhuniProducts } from "./radhuniProducts";
import { shaanGroceryProducts, shaanFrozenProducts } from "./shaanProducts";
import { drinksProducts } from "./drinksProducts";
import { mixedBrandProducts } from "./mixedBrandProducts";

export const storeInfo: StoreInfo = {
  name: "Asia Bazaar",
  phone: "+1-703-555-0192",
  address: "7864 Richmond Hwy",
  city: "Alexandria",
  state: "VA",
  zip: "22306",
  email: "info@asiabazaarak.com",
  mapsUrl: "https://maps.google.com/?q=7864+Richmond+Hwy+Alexandria+VA+22306",
  mapsEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3109.5!2d-77.1000!3d38.7300!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2s7864+Richmond+Hwy+Alexandria+VA!5e0!3m2!1sen!2sus!4v1680000000000",
  social: {
    facebook: "https://facebook.com/asiabazaarva",
    instagram: "https://instagram.com/asiabazaarva",
    whatsapp: "https://wa.me/17035550192",
  },
};

export const storeHours: StoreHours[] = [
  { day: "Monday", open: "9:00 AM", close: "9:00 PM" },
  { day: "Tuesday", open: "9:00 AM", close: "9:00 PM" },
  { day: "Wednesday", open: "9:00 AM", close: "9:00 PM" },
  { day: "Thursday", open: "9:00 AM", close: "9:00 PM" },
  { day: "Friday", open: "9:00 AM", close: "10:00 PM" },
  { day: "Saturday", open: "8:00 AM", close: "10:00 PM" },
  { day: "Sunday", open: "9:00 AM", close: "8:00 PM" },
];

export const categories: Category[] = [
  {
    id: "fresh-meat-fish",
    slug: "fresh-meat-fish",
    label: "Fresh Meat & Fish",
    description: "Daily fresh halal chicken, goat, beef & Bangladeshi fish",
    icon: "Fish",
    href: "/fresh-meat-fish",
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80",
    count: 18,
    color: "#DC2626",
  },
  {
    id: "grocery",
    slug: "grocery",
    label: "Grocery",
    description: "Rice, spices, lentils, oil & all your pantry essentials",
    icon: "ShoppingBasket",
    href: "/grocery",
    image:
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
    count: 45,
    color: "#F59E0B",
  },
  {
    id: "frozen-food",
    slug: "frozen-food",
    label: "Frozen Food",
    description: "Paratha, samosa, frozen fish & ready-to-cook items",
    icon: "Snowflake",
    href: "/frozen-food",
    image:
      "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=600&q=80",
    count: 22,
    color: "#0891B2",
  },
  {
    id: "fresh-produce",
    slug: "fresh-produce",
    label: "Fresh Produce",
    description: "Vegetables, fruits & fresh herbs from local farms",
    icon: "Leaf",
    href: "/shop",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80",
    count: 30,
    color: "#16A34A",
  },
  {
    id: "appliances",
    slug: "appliances",
    label: "Appliances",
    description: "Rice cookers, blenders & kitchen tools",
    icon: "Plug",
    href: "/shop",
    image:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
    count: 12,
    color: "#7C3AED",
  },
  {
    id: "religious",
    slug: "religious",
    label: "Religious & More",
    description: "Prayer mats, incense, holy books & desi clothing",
    icon: "Star",
    href: "/shop",
    image:
      "https://images.unsplash.com/photo-1609183480405-5ba85f5a0148?w=600&q=80",
    count: 20,
    color: "#D97706",
  },
  {
    id: "drinks",
    slug: "drinks",
    label: "Drinks",
    description: "Coca-Cola, Sprite, Pepsi, Rooh Afza, Maaza, Frooti & more",
    icon: "GlassWater",
    href: "/drinks",
    image:
      "https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=600&q=80",
    count: 36,
    color: "#0891B2",
  },
];

export const products: Product[] = [
  // ── CHICKEN ──────────────────────────────────────────────────────────────
  {
    id: "ch-1",
    slug: "zabiha-whole-chicken",
    name: "Zabiha Whole Chicken",
    namebn: "জবাই মুরগি (পুরো)",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 2.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Hand-slaughtered zabiha whole chicken. Freshly dressed every morning. Antibiotic-free.",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    featured: true,
    inStock: true,
  },
  {
    id: "ch-2",
    slug: "regular-whole-chicken",
    name: "Regular Whole Chicken",
    namebn: "পুরো মুরগি",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 2.49,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal whole chicken. Cleaned and dressed daily. Perfect for roasting or curry.",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "ch-3",
    slug: "chicken-leg-thighs",
    name: "Chicken Leg & Thighs",
    namebn: "মুরগির রান ও থাই",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 1.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal chicken leg & thigh pieces. Juicy dark meat, perfect for bhuna and curry.",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "ch-4",
    slug: "chicken-boneless",
    name: "Chicken Boneless",
    namebn: "হাড়হীন মুরগি",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 3.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Boneless halal chicken breast & thigh. Trimmed and ready to cook. Great for kebab, karahi & stir fry.",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    featured: true,
    inStock: true,
  },
  {
    id: "ch-5",
    slug: "chicken-leg-thighs-full-box",
    name: "Leg & Thighs Full Box",
    namebn: "রান ও থাই পুরো বাক্স",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 65.00,
    unit: "per box",
    badge: "SALE",
    description: "Full box of halal chicken leg & thighs. Best value for bulk buyers and large families.",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "ch-6",
    slug: "hand-cut-leg-thighs",
    name: "Hand Cut Leg & Thighs",
    namebn: "হাতে কাটা রান ও থাই",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 2.19,
    unit: "per lb",
    badge: "HALAL",
    description: "Hand-cut halal chicken leg & thighs. Traditional butcher-style cutting for authentic desi cooking.",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    featured: false,
    inStock: true,
  },
  // ── BEEF ─────────────────────────────────────────────────────────────────
  {
    id: "bf-1",
    slug: "beef-mix",
    name: "Beef Mix",
    namebn: "গরুর মাংস মিক্স",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 4.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Mixed halal beef cuts — ideal for curry, stew, and everyday cooking.",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&q=80",
    featured: true,
    inStock: true,
  },
  {
    id: "bf-2",
    slug: "beef-t-bone",
    name: "Beef T-Bone",
    namebn: "গরুর টি-বোন",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 5.59,
    unit: "per lb",
    badge: "HALAL",
    description: "Premium halal T-bone beef. Rich marbling, great for grilling and pan-searing.",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "bf-3",
    slug: "beef-boneless",
    name: "Beef Boneless",
    namebn: "হাড়হীন গরুর মাংস",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 6.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Boneless halal beef. Lean and tender — perfect for kebab, bhuna, and karahi.",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "bf-4",
    slug: "beef-keema",
    name: "Beef Keema",
    namebn: "গরুর কিমা",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 6.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Freshly ground halal beef. Made to order — perfect for keema curry, paratha stuffing and shami kebab.",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "bf-5",
    slug: "beef-nihari",
    name: "Beef Nihari",
    namebn: "গরুর নিহারি কাট",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 5.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Halal beef shank cut specially for nihari. Slow-cook for tender, flavourful results.",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "bf-6",
    slug: "beef-liver-heart",
    name: "Beef Liver & Heart",
    namebn: "গরুর কলিজা ও হার্ট",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 3.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal beef liver and heart. Rich in iron — popular for masala fry and bhuna.",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&q=80",
    featured: false,
    inStock: true,
  },
  // ── FISH ─────────────────────────────────────────────────────────────────
  {
    id: "fi-1",
    slug: "hilsha-15-20",
    name: "Hilsha 15/20",
    namebn: "ইলিশ ১৫/২০",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 14.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Premium Hilsha (Ilish) — largest size, 15–20 pieces per box. Rich, oily and full of flavour. The finest grade.",
    image: "/hilsha.webp",
    featured: true,
    inStock: true,
  },
  {
    id: "fi-2",
    slug: "hilsha-12-15",
    name: "Hilsha 12/15",
    namebn: "ইলিশ ১২/১৫",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 12.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Hilsha 12–15 count. Medium-large size with excellent fat content — perfect for steaming and mustard curry.",
    image: "/hilsha.webp",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-3",
    slug: "hilsha-10-12",
    name: "Hilsha 10/12",
    namebn: "ইলিশ ১০/১২",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 11.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Hilsha 10–12 count. Great everyday size — flavourful and ideal for bhuna, paturi and steaming.",
    image: "/hilsha.webp",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-4",
    slug: "hilsha-8-10",
    name: "Hilsha 8/10",
    namebn: "ইলিশ ৮/১০",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 10.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Hilsha 8–10 count. Generous portion size — popular for family meals and festive cooking.",
    image: "/hilsha.webp",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-5",
    slug: "hilsha-5-8",
    name: "Hilsha 5/8",
    namebn: "ইলিশ ৫/৮",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 8.49,
    unit: "per lb",
    badge: "FRESH",
    description: "Hilsha 5–8 count — smaller pieces, great value. Still full of that signature Ilish flavour.",
    image: "/hilsha.webp",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-6",
    slug: "swai-fish",
    name: "Swai Fish",
    namebn: "সোয়াই মাছ",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 5.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Swai (pangasius) fish. Mild white fish, great for frying, grilling and light curries.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-7",
    slug: "mrigel-fish",
    name: "Mrigel",
    namebn: "মৃগেল মাছ",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 4.49,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Mrigel (Cirrhinus cirrhosus) — a classic desi carp. Sweet, clean taste, loved in Bengali cooking.",
    image: "https://images.unsplash.com/photo-1510130387422-82bed34b37e9?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-8",
    slug: "shor-puti-fish",
    name: "Shor Puti",
    namebn: "শর পুটি মাছ",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 2.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Shor Puti — a small, bony but intensely flavourful Bangladeshi fish. Best fried crispy.",
    image: "https://images.unsplash.com/photo-1510130387422-82bed34b37e9?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-9",
    slug: "katla-fish",
    name: "Katla",
    namebn: "কাতলা মাছ",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 3.49,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Katla — large, meaty carp. Ideal for mustard gravy, doi maach and festive Bengali cooking.",
    image: "/katla-fish.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-10",
    slug: "rohu-2-3kg",
    name: "Rohu 2/3 kg",
    namebn: "রুই মাছ ২/৩ কেজি",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 2.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Rohu fish, 2–3 kg size. Classic desi carp — perfect for bhuna, jhol and mustard curry.",
    image: "/rohu-fish.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "fi-11",
    slug: "rohu-3-4kg",
    name: "Rohu 3/4 kg",
    namebn: "রুই মাছ ৩/৪ কেজি",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 3.49,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh large Rohu fish, 3–4 kg size. Bigger portions with more meat — great for family feasts.",
    image: "/rohu-fish.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-12",
    slug: "koral-large",
    name: "Koral (Large)",
    namebn: "কোরাল মাছ (বড়)",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 6.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Large Koral (Barramundi/Asian sea bass). Firm, delicate white flesh — premium fish for special occasions.",
    image: "/koral-fish.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "fi-13",
    slug: "koral-medium-small",
    name: "Koral (Medium/Small)",
    namebn: "কোরাল মাছ (মাঝারি/ছোট)",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 4.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Medium to small Koral (Barramundi). Mild flavour, excellent for frying and light masala curry.",
    image: "/koral-fish.jpg",
    featured: false,
    inStock: true,
  },
  // ── BABY GOAT ────────────────────────────────────────────────────────────
  {
    id: "gt-1",
    slug: "baby-goat-whole",
    name: "Baby Goat Whole",
    namebn: "পুরো খাসি (ছাগলের বাচ্চা)",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 11.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Whole baby goat, freshly slaughtered halal. Tender and lean — ideal for full roast and special occasions.",
    image: "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=600&q=80",
    featured: true,
    inStock: true,
  },
  {
    id: "gt-2",
    slug: "baby-goat-half",
    name: "Baby Goat Half",
    namebn: "আধা খাসি",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 12.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Half baby goat — front or back cut available. Fresh, tender halal meat for biryani and rezala.",
    image: "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "gt-3",
    slug: "baby-goat-shoulder",
    name: "Goat Shoulder",
    namebn: "খাসির কাঁধ",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 12.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Baby goat shoulder cut. Bone-in, well-marbled — slow-cook for rich, fall-off-the-bone results.",
    image: "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "gt-4",
    slug: "baby-goat-leg",
    name: "Goat Leg",
    namebn: "খাসির রান",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 13.49,
    unit: "per lb",
    badge: "HALAL",
    description: "Baby goat leg — premium cut. Lean and tender. Perfect roasted whole or in a rich biryani.",
    image: "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "gt-5",
    slug: "goat-liver-heart-kidney",
    name: "Goat Liver, Heart & Kidney",
    namebn: "খাসির কলিজা, হার্ট ও কিডনি",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 10.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal baby goat offal — liver, heart and kidney together. Excellent for masala fry and bhuna.",
    image: "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=600&q=80",
    featured: false,
    inStock: true,
  },
  // ── OTHER CUTS ───────────────────────────────────────────────────────────
  {
    id: "ot-1",
    slug: "goat-feet",
    name: "Goat Feet",
    namebn: "খাসির পায়া",
    category: "fresh-meat-fish",
    subcategory: "other",
    price: 7.49,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal goat trotters (paya). Slow-cooked paya soup is a beloved desi winter dish.",
    image: "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "ot-2",
    slug: "beef-feet",
    name: "Beef Feet",
    namebn: "গরুর পায়া",
    category: "fresh-meat-fish",
    subcategory: "other",
    price: 4.49,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal beef trotters. Rich in collagen — makes a deeply nourishing paya broth and nihari base.",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&q=80",
    featured: false,
    inStock: true,
  },
  // ── ORGANIC ──────────────────────────────────────────────────────────────
  {
    id: "og-1",
    slug: "organic-chicken-breast",
    name: "Organic Chicken Breast",
    namebn: "অর্গানিক মুরগির বুক",
    category: "fresh-meat-fish",
    subcategory: "organic",
    price: 4.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Certified organic, free-range halal chicken breast. No antibiotics, no hormones — pure and clean.",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "og-2",
    slug: "organic-whole-chicken-full-box",
    name: "Organic Whole Chicken Full Box",
    namebn: "অর্গানিক পুরো মুরগি (বাক্স)",
    category: "fresh-meat-fish",
    subcategory: "organic",
    price: 115.00,
    unit: "40 lb box",
    badge: "SALE",
    description: "Bulk box of organic whole halal chickens — 40 lbs. Best value for restaurants and large families.",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "og-3",
    slug: "regular-whole-chicken-full-box",
    name: "Regular Whole Chicken Full Box",
    namebn: "নিয়মিত পুরো মুরগি (বাক্স)",
    category: "fresh-meat-fish",
    subcategory: "organic",
    price: 155.00,
    unit: "70 lb box",
    badge: "SALE",
    description: "Bulk box of regular halal whole chickens — 70 lbs. Ideal for catering, events and wholesale buyers.",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80",
    featured: false,
    inStock: true,
  },
  // Grocery
  {
    id: "7",
    slug: "basmati-rice",
    name: "Basmati Rice",
    category: "grocery",
    subcategory: "rice",
    price: 24.99,
    unit: "10kg bag",
    badge: "HOT",
    description:
      "Premium aged Basmati rice. Long grain, fragrant, perfect for biryani.",
    image:
      "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=600&q=80",
    featured: true,
    inStock: true,
  },
  {
    id: "8",
    slug: "kalijeera-rice",
    name: "Kalijeera Rice",
    namebn: "কালিজিরা চাল",
    category: "grocery",
    subcategory: "rice",
    price: 19.99,
    unit: "5kg bag",
    description: "Aromatic Bangladeshi Kalijeera rice. Naturally fragrant.",
    image:
      "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "9",
    slug: "shaan-masala-pack",
    name: "Shaan Masala Variety",
    category: "grocery",
    subcategory: "spices",
    price: 3.49,
    unit: "per pack",
    badge: "NEW",
    description:
      "Authentic Shaan masala blends — Biryani, Karahi, Nihari & more.",
    image:
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
    featured: true,
    inStock: true,
  },
  {
    id: "10",
    slug: "mustard-oil",
    name: "Mustard Oil",
    namebn: "সরিষার তেল",
    category: "grocery",
    subcategory: "oil",
    price: 8.99,
    unit: "1L bottle",
    description: "Pure cold-pressed mustard oil. Essential for Bengali cooking.",
    image:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "11",
    slug: "dal-masoor",
    name: "Masoor Dal (Red Lentils)",
    namebn: "মসুর ডাল",
    category: "grocery",
    subcategory: "lentils",
    price: 5.99,
    unit: "2kg bag",
    description:
      "Premium red lentils. Quick-cooking, nutritious & full of flavor.",
    image:
      "https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "12",
    slug: "atta-flour",
    name: "Whole Wheat Atta",
    category: "grocery",
    subcategory: "flour",
    price: 12.99,
    unit: "5kg bag",
    description: "Fine-ground whole wheat atta for rotis and parathas.",
    image:
      "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80",
    featured: false,
    inStock: true,
  },
  // Frozen Food
  {
    id: "13",
    slug: "frozen-paratha",
    name: "Frozen Paratha (20pc)",
    namebn: "পরোটা",
    category: "frozen-food",
    subcategory: "bread",
    price: 7.99,
    unit: "pack of 20",
    badge: "HOT",
    description:
      "Flaky, layered frozen parathas. Ready in minutes on the tawa.",
    image:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80",
    featured: true,
    inStock: true,
  },
  {
    id: "14",
    slug: "frozen-samosa",
    name: "Frozen Samosa (12pc)",
    category: "frozen-food",
    subcategory: "snacks",
    price: 6.49,
    unit: "pack of 12",
    badge: "HOT",
    description: "Crispy potato & pea samosas. Perfect party snack.",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80",
    featured: true,
    inStock: true,
  },
  {
    id: "15",
    slug: "frozen-fish",
    name: "Frozen Hilsa Fish",
    namebn: "হিমায়িত ইলিশ",
    category: "frozen-food",
    subcategory: "fish",
    price: 18.99,
    unit: "1kg pack",
    description:
      "Imported frozen Ilish fish. Flash-frozen to preserve flavor.",
    image:
      "/hilsha.webp",
    featured: false,
    inStock: true,
  },
  {
    id: "16",
    slug: "frozen-spring-rolls",
    name: "Frozen Spring Rolls (20pc)",
    category: "frozen-food",
    subcategory: "snacks",
    price: 8.49,
    unit: "pack of 20",
    description: "Vegetable spring rolls — crispy, golden, delicious.",
    image:
      "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=600&q=80",
    featured: false,
    inStock: true,
  },
  // Fresh Produce
  {
    id: "17",
    slug: "green-chili",
    name: "Green Chili",
    namebn: "কাঁচা মরিচ",
    category: "fresh-produce",
    subcategory: "herbs",
    price: 1.99,
    unit: "per bunch",
    badge: "FRESH",
    description: "Fresh hot green chilies. Essential for desi cooking.",
    image:
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80",
    featured: false,
    inStock: true,
  },
  {
    id: "18",
    slug: "cilantro",
    name: "Cilantro (Dhania)",
    namebn: "ধনেপাতা",
    category: "fresh-produce",
    subcategory: "herbs",
    price: 0.99,
    unit: "per bunch",
    badge: "FRESH",
    description: "Fresh cilantro / coriander leaves. Aromatic and bright.",
    image:
      "https://images.unsplash.com/photo-1587814213716-0068738d0fa4?w=600&q=80",
    featured: false,
    inStock: true,
  },
];

export const deals: Deal[] = [
  {
    id: "d1",
    title: "4 PCS Ilish Fish Combo",
    description:
      "Get 4 pieces of fresh Ilish (Hilsa) fish — the king of Bangladeshi fish. Limited quantity daily.",
    price: 25,
    originalPrice: 36,
    savings: 11,
    image:
      "/hilsha.webp",
    badge: "TODAY'S DEAL",
  },
  {
    id: "d2",
    title: "Weekend Meat Bundle",
    description:
      "2 lbs Halal Goat + 2 lbs Halal Chicken. Perfect for weekend biryani.",
    price: 45,
    originalPrice: 60,
    savings: 15,
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80",
    badge: "WEEKEND SPECIAL",
  },
  {
    id: "d3",
    title: "Grocery Starter Pack",
    description:
      "10kg Basmati Rice + 6 Shaan Masala packs + 2L Mustard Oil. Everything you need.",
    price: 49.99,
    originalPrice: 65,
    savings: 15,
    image:
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
    badge: "BEST VALUE",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    author: "Fatema Khanom",
    rating: 5,
    date: "March 2025",
    body: "Best place for fresh fish and desi groceries. The Ilish fish is always fresh and the prices are very reasonable. Highly recommended for all Bangladeshis in the area!",
    verified: true,
  },
  {
    id: "r2",
    author: "Mohammad Rahman",
    rating: 5,
    date: "February 2025",
    body: "I drive 30 minutes just to shop here. The halal meat quality is exceptional — you can taste the difference. Friendly staff who understand what you need.",
    verified: true,
  },
  {
    id: "r3",
    author: "Nasrin Ahmed",
    rating: 5,
    date: "January 2025",
    body: "Finally a proper desi store in Alexandria! They have everything — Shaan masala, Kalijeera rice, frozen paratha and even prayer mats. One-stop shop!",
    verified: true,
  },
  {
    id: "r4",
    author: "Karim Uddin",
    rating: 4,
    date: "December 2024",
    body: "Great selection of Bangladeshi and Pakistani products. The goat biryani combo deal was worth every penny. Will definitely be back every weekend.",
    verified: true,
  },
];

export const announcementMessages = [
  "🚚 Same-Day Pickup Available",
  "🐟 Fresh Ilish Fish In Stock Daily",
  "🥩 Fresh Halal Meat Slaughtered Daily",
  "📞 Call to Order: " + storeInfo.phone,
  "📍 7864 Richmond Hwy, Alexandria VA",
  "🕌 Prayer Mats & Islamic Items In Stock",
];

// ── NANAK PRODUCTS ────────────────────────────────────────────────────────
const nanakProducts: Product[] = [
  {
    id: "nanak-1",
    slug: "nanak-pure-desi-ghee",
    name: "Nanak Pure Desi Ghee 400g",
    category: "grocery",
    subcategory: "ghee",
    price: 9.99,
    unit: "400g",
    badge: "HOT",
    description: "Nanak Pure Desi Ghee — made from 100% pure cow milk. Rich aroma, golden colour. Perfect for cooking, tadka and halwa.",
    image: "https://images.squarespace-cdn.com/content/v1/62df38bd768870226dced4a0/1663721053226-19KTB77V2NLCIXHCTAE0/Effects3.jpg?format=2500w",
    featured: true,
    inStock: true,
    brand: "Nanak",
  },
  {
    id: "nanak-2",
    slug: "nanak-paneer",
    name: "Nanak Paneer 400g",
    category: "grocery",
    subcategory: "dairy",
    price: 5.99,
    unit: "400g",
    badge: "FRESH",
    description: "Nanak fresh Paneer — soft, firm and perfect for palak paneer, paneer tikka, karahi and curries.",
    image: "https://static1.squarespace.com/static/62df38bd768870226dced4a0/62ecd969d0402a7f85047496/6358556938df077c077cb8b4/1687365484774/paneer-722.jpg?format=2500w",
    featured: true,
    inStock: true,
    brand: "Nanak",
  },
  {
    id: "nanak-3",
    slug: "nanak-rasmalai",
    name: "Nanak Rasmalai 1kg",
    category: "grocery",
    subcategory: "sweets",
    price: 8.99,
    unit: "1kg",
    badge: "HOT",
    description: "Nanak Rasmalai — soft, spongy cheese dumplings soaked in sweetened, cardamom-flavoured cream. A classic South Asian dessert.",
    image: "https://static1.squarespace.com/static/62df38bd768870226dced4a0/62ecd969d0402a7f85047496/631cd0d063eb30325ae82773/1687883413545/rasmalai-413.png?format=2500w",
    featured: true,
    inStock: true,
    brand: "Nanak",
  },
  {
    id: "nanak-4",
    slug: "nanak-gulab-jamun",
    name: "Nanak Gulab Jamun 1kg",
    category: "grocery",
    subcategory: "sweets",
    price: 8.99,
    unit: "1kg",
    badge: "HOT",
    description: "Nanak Gulab Jamun — soft milk-solid dumplings drenched in rose-scented sugar syrup. Ready to serve warm or cold.",
    image: "https://images.squarespace-cdn.com/content/v1/62df38bd768870226dced4a0/1662832510308-M13A7PC9BA5GY181AXUJ/GulabjamunProp.jpg?format=2500w",
    featured: false,
    inStock: true,
    brand: "Nanak",
  },
  {
    id: "nanak-5",
    slug: "nanak-gajar-halwa",
    name: "Nanak Gajar Halwa 850g",
    category: "grocery",
    subcategory: "sweets",
    price: 7.99,
    unit: "850g",
    badge: "NEW",
    description: "Nanak Gajar Halwa — slow-cooked shredded carrots in pure ghee, milk and sugar, flavoured with cardamom and garnished with nuts.",
    image: "https://images.squarespace-cdn.com/content/v1/62df38bd768870226dced4a0/1735590096975-J6XUT4GR6AQRGB6I1JUE/Gajar+Halwa2.jpg?format=2500w",
    featured: false,
    inStock: true,
    brand: "Nanak",
  },
];

// Merge brand products
(products as Product[]).push(...deepFoodsGroceryProducts, ...deepFoodsFrozenProducts, ...radhuniProducts, ...shaanGroceryProducts, ...shaanFrozenProducts, ...drinksProducts, ...nanakProducts, ...mixedBrandProducts);

// Query utilities
export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter((p) => p.brand === brand);
}
