import type { Product } from "@/types";

// Image constants
const hilsha    = "https://ik.imagekit.io/3u72arpq9/product-image/3412_1722260179_Kolkata_Hilsa__600g_-_750g_.jpg";
const hilshaSmall = "https://ik.imagekit.io/3u72arpq9/product-image/6181_1746003232_2806_1699361623_CompressJPEG.Online_100kb_129309.jpg";
const rohu      = "https://ik.imagekit.io/3u72arpq9/product-image/2917_1694760703_Rohu_image.jpg";
const bhetki    = "https://ik.imagekit.io/3u72arpq9/product-image/1359_1694761438_Bhetki_Fillet_new.jpg";
const swai      = "https://jds.market/wp-content/uploads/2024/11/swai-whole-fish.webp";
const chickenWhole  = "https://onestophalal.com/cdn/shop/products/halal_chicken_whole_1.jpg?v=1578097153";
const chickenRegular = "https://taibahalalmeat.com/wp-content/uploads/2025/03/10.75-600x464.jpg";
const chickenLegThigh = "https://halalmeatnj.com/cdn/shop/files/istockphoto-1177903289-612x612.jpg?v=1740430670&width=1946";
const chickenBoneless = "https://onestophalal.com/cdn/shop/products/halal_chicken_breast_1.jpg?v=1578096921";
const beefMix   = "https://taibahalalmeat.com/wp-content/uploads/2025/03/59494949-300x300.jpg";
const beefTbone = "https://taibahalalmeat.com/wp-content/uploads/2025/05/d776df4df4805d6fac1860001aa270c4.jpg";
const beefBoneless = "https://taibahalalmeat.com/wp-content/uploads/2025/03/lb-Packed-Fresh-300x300.jpg";
const beefKeema = "https://taibahalalmeat.com/wp-content/uploads/2025/03/lb-300x300.jpg";
const goat      = "https://onestophalal.com/cdn/shop/products/half_goat_1_d681ad20-bbc9-4945-b50c-c5027900c599.jpg";
const goatLeg   = "https://onestophalal.com/cdn/shop/products/zabiha_halal_goat_leg_whole_3.jpg?v=1628631693";

export const freshMeatProducts: Product[] = [
  // ── CHICKEN (additional cuts) ───────────────────────────────────────────
  {
    id: "meat-07",
    slug: "regular-whole-chicken",
    name: "Regular Whole Chicken",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 2.49,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh whole chicken. Cleaned and ready to cook.",
    image: chickenRegular,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-08",
    slug: "chicken-leg-thighs",
    name: "Chicken Leg & Thighs",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 1.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal chicken leg and thighs. Great for curry and BBQ.",
    image: chickenLegThigh,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-09",
    slug: "chicken-boneless",
    name: "Chicken Boneless",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 3.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal boneless chicken breast. Lean, clean, tender.",
    image: chickenBoneless,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-10",
    slug: "chicken-leg-thighs-full-box",
    name: "Leg & Thighs Full Box",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 65.00,
    unit: "per box",
    badge: "SALE",
    description: "Full box of fresh halal chicken leg & thighs. Best value for large families and restaurants.",
    image: chickenLegThigh,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-11",
    slug: "hand-cut-leg-thighs",
    name: "Hand Cut Leg & Thighs",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 2.19,
    unit: "per lb",
    badge: "HALAL",
    description: "Hand cut zabiha halal chicken leg & thighs. Butchered fresh daily.",
    image: chickenLegThigh,
    featured: false,
    inStock: true,
  },

  // ── BEEF (additional cuts) ───────────────────────────────────────────────
  {
    id: "meat-12",
    slug: "beef-t-bone",
    name: "Beef T-Bone",
    namebn: "টি-বোন বিফ",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 5.59,
    unit: "per lb",
    badge: "HALAL",
    description: "Premium halal beef T-bone steak. Perfect for grilling and BBQ.",
    image: beefTbone,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-13",
    slug: "beef-boneless",
    name: "Beef Boneless",
    namebn: "বোনলেস বিফ",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 6.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal boneless beef. Ideal for kebabs, curries and biryanis.",
    image: beefBoneless,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-14",
    slug: "beef-keema",
    name: "Beef Keema",
    namebn: "কিমা",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 6.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal ground beef (keema). Perfect for shami kabab, keema curry and pasta.",
    image: beefKeema,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-15",
    slug: "beef-nihari",
    name: "Beef Nihari Cut",
    namebn: "নিহারি",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 5.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Halal beef nihari cut — shank and marrow bones. Slow-cook for rich, thick nihari stew.",
    image: beefMix,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-16",
    slug: "beef-liver-heart",
    name: "Beef Liver & Heart",
    namebn: "কলিজা ও হার্ট",
    category: "fresh-meat-fish",
    subcategory: "beef",
    price: 3.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal beef liver and heart. Nutritious and full of flavour.",
    image: beefMix,
    featured: false,
    inStock: true,
  },

  // ── FISH (additional species & sizes) ───────────────────────────────────
  {
    id: "meat-17",
    slug: "hilsha-15-20",
    name: "Hilsha 15/20",
    namebn: "ইলিশ ১৫/২০",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 14.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Premium Hilsha (Ilish) — large 15 to 20 pieces per unit. The finest size for festive cooking.",
    image: hilsha,
    featured: true,
    inStock: true,
  },
  {
    id: "meat-18",
    slug: "hilsha-10-12",
    name: "Hilsha 10/12",
    namebn: "ইলিশ ১০/১২",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 11.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Hilsha (Ilish) fish, 10 to 12 per unit. Rich, oily, full of flavour.",
    image: hilsha,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-19",
    slug: "hilsha-8-10",
    name: "Hilsha 8/10",
    namebn: "ইলিশ ৮/১০",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 10.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Hilsha (Ilish), 8 to 10 per unit. Perfect size for sorshe ilish.",
    image: hilsha,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-20",
    slug: "hilsha-5-8",
    name: "Hilsha 5/8",
    namebn: "ইলিশ ৫/৮",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 8.49,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Hilsha (Ilish), 5 to 8 per unit. Great for everyday Bengali cooking.",
    image: hilshaSmall,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-21",
    slug: "swai-fish",
    name: "Swai Fish",
    namebn: "শ্বাই মাছ",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 5.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Swai fish — mild flavour, tender flesh. Great for curry and fry.",
    image: swai,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-22",
    slug: "mrigel-fish",
    name: "Mrigel",
    namebn: "মৃগেল",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 4.49,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Mrigel (Mrigal carp) — popular South Asian freshwater fish. Perfect for mustard curry.",
    image: rohu,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-23",
    slug: "shor-puti-fish",
    name: "Shor Puti",
    namebn: "শোর পুঁটি",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 2.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Fresh Shor Puti — small Bangladeshi freshwater fish. Loved for its delicate flavour.",
    image: rohu,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-24",
    slug: "koral-fish-large",
    name: "Koral (Large)",
    namebn: "কোরাল বড়",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 6.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Large fresh Koral (Snakehead) fish — firm white flesh, excellent for curry and grilling.",
    image: bhetki,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-25",
    slug: "koral-fish-medium-small",
    name: "Koral (Medium/Small)",
    namebn: "কোরাল মাঝারি",
    category: "fresh-meat-fish",
    subcategory: "fish",
    price: 4.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Medium to small fresh Koral (Snakehead) fish. Great for whole fish preparation.",
    image: bhetki,
    featured: false,
    inStock: true,
  },

  // ── BABY GOAT ────────────────────────────────────────────────────────────
  {
    id: "meat-26",
    slug: "baby-goat-whole",
    name: "Baby Goat Whole",
    namebn: "পুরো ছাগল",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 11.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Whole fresh halal baby goat. Ideal for Eid, Qurbani and special occasions.",
    image: goat,
    featured: true,
    inStock: true,
  },
  {
    id: "meat-27",
    slug: "baby-goat-half",
    name: "Baby Goat Half",
    namebn: "অর্ধেক ছাগল",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 12.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal baby goat half. Perfect for biryani and rezala.",
    image: goat,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-28",
    slug: "baby-goat-shoulder",
    name: "Baby Goat Shoulder",
    namebn: "কাঁধের মাংস",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 12.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal baby goat shoulder — slow-cook for tender, flavourful results.",
    image: goat,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-29",
    slug: "baby-goat-leg",
    name: "Baby Goat Leg",
    namebn: "রানের মাংস",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 13.49,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal baby goat leg — perfect for roasting and whole-piece curry.",
    image: goatLeg,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-30",
    slug: "baby-goat-organ-mix",
    name: "Goat Liver + Heart + Kidney",
    namebn: "কলিজা + হার্ট + কিডনি",
    category: "fresh-meat-fish",
    subcategory: "goat",
    price: 10.99,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal goat organ mix — liver, heart and kidney. A desi delicacy.",
    image: goat,
    featured: false,
    inStock: true,
  },

  // ── OTHER ────────────────────────────────────────────────────────────────
  {
    id: "meat-31",
    slug: "goat-feet",
    name: "Goat Feet",
    namebn: "পায়া",
    category: "fresh-meat-fish",
    subcategory: "other",
    price: 7.49,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal goat feet (paya). Slow-cook for rich collagen-packed paya soup.",
    image: goat,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-32",
    slug: "beef-feet",
    name: "Beef Feet",
    namebn: "গরুর পায়া",
    category: "fresh-meat-fish",
    subcategory: "other",
    price: 4.49,
    unit: "per lb",
    badge: "HALAL",
    description: "Fresh halal beef feet. Perfect for paya nihari and bone broth.",
    image: beefMix,
    featured: false,
    inStock: true,
  },

  // ── ORGANIC ──────────────────────────────────────────────────────────────
  {
    id: "meat-33",
    slug: "organic-chicken-breast",
    name: "Organic Chicken Breast",
    category: "fresh-meat-fish",
    subcategory: "organic",
    price: 4.99,
    unit: "per lb",
    badge: "FRESH",
    description: "Certified organic halal chicken breast — antibiotic free, hormone free, vegetarian fed.",
    image: chickenBoneless,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-34",
    slug: "organic-whole-chicken-full-box",
    name: "Organic Whole Chicken Full Box (40 lbs)",
    category: "fresh-meat-fish",
    subcategory: "organic",
    price: 115.00,
    unit: "per box",
    badge: "SALE",
    description: "Organic halal whole chicken full box — 40 lbs. Best value for restaurants and large families.",
    image: chickenWhole,
    featured: false,
    inStock: true,
  },
  {
    id: "meat-35",
    slug: "regular-whole-chicken-full-box",
    name: "Regular Whole Chicken Full Box (70 lbs)",
    category: "fresh-meat-fish",
    subcategory: "chicken",
    price: 155.00,
    unit: "per box",
    badge: "SALE",
    description: "Regular halal whole chicken full box — 70 lbs. Bulk discount for restaurants.",
    image: chickenWhole,
    featured: false,
    inStock: true,
  },
];
